apiVersion: v1
entries:
  camel-dashboard-console:
  - annotations:
      charts.openshift.io/name: Camel Dashboard OpenShift Console plugin
    apiVersion: v2
    appVersion: 0.5.0
    created: "2026-05-29T17:39:42.64820157+02:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 093047cefbf71573a5412ca41921dc28dbd0417fd5981eb18013c21b95d687fe
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://github.com/camel-tooling/camel-dashboard/raw/main/docs/static/images/logo.png
    keywords:
    - camel
    - dashboard
    - console
    - react
    kubeVersion: '>= 1.34'
    maintainers:
    - email: gfournier@apache.org
      name: gansheer
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.5.0.tgz
    version: 0.5.0
generated: "2026-05-29T17:39:42.647539248+02:00"
