apiVersion: v1
entries:
  camel-dashboard-console:
  - annotations:
      charts.openshift.io/name: Camel Dashboard OpenShift Console plugin
    apiVersion: v2
    appVersion: 0.4.1
    created: "2026-03-20T15:01:38.562386933+01:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 1df0e433f43ff4af4854c34a47a0f31e9a8bbad73292b8d61bb473bbbc4f1dea
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://github.com/camel-tooling/camel-dashboard/raw/main/docs/static/images/logo.png
    keywords:
    - camel
    - dashboard
    - console
    - react
    kubeVersion: '>= 1.34'
    maintainers:
    - email: gfournier@apache.org
      name: gansheer
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.4.1.tgz
    version: 0.4.1
generated: "2026-03-20T15:01:38.561917383+01:00"
