apiVersion: v1
entries:
  camel-dashboard-console:
  - annotations:
      charts.openshift.io/name: Camel Dashboard OpenShift Console plugin
    apiVersion: v2
    appVersion: 0.4.2
    created: "2026-03-27T16:42:03.159141676+01:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 5ee9e3f91ef2b27e92300f61d3659e0a66c58147772e8eb39180547b56d0b87d
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://github.com/camel-tooling/camel-dashboard/raw/main/docs/static/images/logo.png
    keywords:
    - camel
    - dashboard
    - console
    - react
    kubeVersion: '>= 1.34'
    maintainers:
    - email: gfournier@apache.org
      name: gansheer
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.4.2.tgz
    version: 0.4.2
generated: "2026-03-27T16:42:03.158555297+01:00"
