name: Build

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'web/yarn.lock'

      - name: Build plugin
        run: make plugin-build

      - name: Lint plugin
        continue-on-error: true
        run: make plugin-lint

      - name: Log in to registry
        if:  github.ref == 'refs/heads/main'
        id: login-registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build plugin container
        shell: bash
        run: |
          make CUSTOM_PLUGIN_IMAGE=quay.io/camel-tooling/camel-openshift-console-plugin plugin-image

      - name: Push plugin container
        if:  github.ref == 'refs/heads/main'
        shell: bash
        run: |
          make CUSTOM_PLUGIN_IMAGE=quay.io/camel-tooling/camel-openshift-console-plugin push-plugin
